"""empty message

Revision ID: 170721fae10e
Revises: a96ad44084a1
Create Date: 2025-09-19 02:48:52.552508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170721fae10e'
down_revision = 'a96ad44084a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
