"""empty message

Revision ID: 2fc79164132f
Revises: e93ffb5740ab
Create Date: 2025-09-17 23:16:22.907326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc79164132f'
down_revision = 'e93ffb5740ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what', sa.String(length=15), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.Column('where', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
