"""empty message

Revision ID: 41b9d96f61ba
Revises: abfa9958f4d0
Create Date: 2025-09-18 00:22:21.200022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b9d96f61ba'
down_revision = 'abfa9958f4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who', sa.Integer(), nullable=False))
        batch_op.drop_constraint('event_creator_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['who'], ['id'])
        batch_op.drop_column('creator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_creator_fkey', 'user', ['creator'], ['id'])
        batch_op.drop_column('who')

    # ### end Alembic commands ###
