"""empty message

Revision ID: 4e60de783ad8
Revises: bdacb183b144
Create Date: 2025-09-19 23:19:34.622697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e60de783ad8'
down_revision = 'bdacb183b144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
