"""empty message

Revision ID: 79791aaf2729
Revises: 170721fae10e
Create Date: 2025-09-19 03:14:17.540399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79791aaf2729'
down_revision = '170721fae10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_unique_constraint(None, ['best_post'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
