"""empty message

Revision ID: 7ef7d8df6755
Revises: 79791aaf2729
Create Date: 2025-09-19 03:16:19.057811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef7d8df6755'
down_revision = '79791aaf2729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('profile_best_post_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_unique_constraint('profile_best_post_key', ['best_post'])

    # ### end Alembic commands ###
