"""empty message

Revision ID: abfa9958f4d0
Revises: bb6e63ddad59
Create Date: 2025-09-18 00:00:46.746915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfa9958f4d0'
down_revision = 'bb6e63ddad59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.Integer(), nullable=False))
        batch_op.drop_constraint('event_organizer_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator'], ['id'])
        batch_op.drop_column('organizer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_organizer_fkey', 'user', ['organizer'], ['id'])
        batch_op.drop_column('creator')

    # ### end Alembic commands ###
