"""empty message

Revision ID: bdacb183b144
Revises: d7ac220d279f
Create Date: 2025-09-19 04:38:33.875690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdacb183b144'
down_revision = 'd7ac220d279f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='follower_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='follower_user_to_id_fkey')
    )
    # ### end Alembic commands ###
